.TH man "cliente"  
.SH NAME
cliente -> Aplicación que permite a un usuatrio interactuar con el mundo pokemon, se requiere tener un usuario registrado, dentro de este programa se podra capturar a los pokemons salvajes del mundo, recuerda que no siempre es sencillo volverse un maestro Pokemon.
.SH SYNOPSIS
.B cliente
[\fIoptions\fR]

.SH DESCRIPTION
Primero se deberá escribir la dirección IP del servidor donde esta el mundo Pokemon(Servidor), posteriormente deberemos escribir nuestro número de usuario para poder tener acceso al mundo Pokemon.
.PP
Este es un párrafo nuevo.
Las nuevas líneas se introducen con .br

.SH BUGS
Aun no se encuentran BUGS
.SH AUTHOR
Barajas Figueroa José de Jesús
.br
Monreal Gamboa Francisco Manuel
.br
Ramirez García Diana Isabel
