.TH man "servidor"  
.SH NAME
servidor -> Aplicación que inicia un mundo Pokemon, el lugar donde se inicie recibira a entrenadores Pokemon anciosos por capturar nuevas criaturas. 
.SH SYNOPSIS
.B servidor

.SH DESCRIPTION
Basta simplemente con iniciar el programa servidor.py, este levantar un serivicio en el puerto 9999 por default, se debe de tener arriba este programa antes de los clientes soliciten conectarse al mundo Pokemon

.SH BUGS
Aun no se encuentran BUGS
.SH AUTHOR
Barajas Figueroa José de Jesús
.br
Monreal Gamboa Francisco Manuel
.br
Ramirez García Diana Isabel
